name: database_repository
description: A database independent repository style implementation
version: 0.1.0

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"
  
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.2